# Generated by Django 5.1.5 on 2025-04-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobileno',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
