# Generated by Django 5.2 on 2025-04-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_customuser'),
        ('accounts', '0007_delete_users'),
    ]

    operations = [
    ]
